### PR TITLE
Refactor to make package installable

### PR DESCRIPTION
**Pull request by yash-s20**
## Overview

Robotouille can be installed by `pip install -e .`

## Changes Made

Shifted main directory files to `robotuille/` and `utils/`, correct imports and paths accordingly

## Test Coverage
TODO

## Next Steps (delete if not applicable)
README needs to be update with new install instructions

## Screenshots (delete if not applicable)

<details>

  <summary>Screen Shot Name</summary>

  
  

</details>

### CODE REVIEW

**Comment by yash-s20** [comment]
I'm not sure why `pddlgym/robotouille/` has extra files. Should they be getting deleted? Possible bug of refactoring

**Comment by yash-s20** [comment]
Removed the files.
Regarding the warning - I tried to find the source of the issue and noticed `register_pddl_env` being called twice for the name "robotouille" in this branch instead of once as in main. Here's all the environments its called for in main - 
```
Gripper
GripperTest
Easygripper
EasygripperTest
Onearmedgripper
OnearmedgripperTest
Tinyonearmedgripper
TinyonearmedgripperTest
Lifelong_tiny_gripper
Lifelong_tiny_gripperTest
Rearrangement
RearrangementTest
Sokoban
SokobanTest
Minecraft
MinecraftTest
Depot
DepotTest
Baking
BakingTest
Blocks
BlocksTest
Derivedblocks
DerivedblocksTest
Toomanyblocks
ToomanyblocksTest
Lifelong_blocks6
Lifelong_blocks6Test
Travel
TravelTest
Doors
DoorsTest
Casino
CasinoTest
Hanoi
HanoiTest
Hanoi_operator_actions
Hanoi_operator_actionsTest
Tsp
TspTest
Tsp_operator_actions
Tsp_operator_actionsTest
Slidetile
SlidetileTest
Elevator
ElevatorTest
Ferry
FerryTest
Meetpass
MeetpassTest
Footwear
FootwearTest
Easyblocks
EasyblocksTest
Conditionalblocks
ConditionalblocksTest
Conditionalferry
ConditionalferryTest
Blocks_operator_actions
Blocks_operator_actionsTest
Generated_blocks
Generated_blocksTest
Blocks_medium
Blocks_mediumTest
Manyblocksnopiles
ManyblocksnopilesTest
Manyexplodingblockssmallpiles
ManyexplodingblockssmallpilesTest
Manyblockssmallpiles
ManyblockssmallpilesTest
Manyblockssmallpilesnoclear
ManyblockssmallpilesnoclearTest
Manyblockssmallpilesnohand
ManyblockssmallpilesnohandTest
Manyblockssmallpilesnoclearhand
ManyblockssmallpilesnoclearhandTest
Quantifiedblocks
QuantifiedblocksTest
Quantifiedblocks2
Quantifiedblocks2Test
Quantifiedblocks3
Quantifiedblocks3Test
Equalityblocks
EqualityblocksTest
Equalityblocks2
Equalityblocks2Test
Manygrid
ManygridTest
Manylogistics
ManylogisticsTest
Manymiconic
ManymiconicTest
Manygripper
ManygripperTest
Manyferry
ManyferryTest
Glibblocks
GlibblocksTest
Glibrearrangement
GlibrearrangementTest
Glibdoors
GlibdoorsTest
Tireworld
TireworldTest
Manytireworld
ManytireworldTest
Fridge
FridgeTest
Snake
SnakeTest
River
RiverTest
Explodingblocks
ExplodingblocksTest
Newspapers
NewspapersTest
Easynewspapers
EasynewspapersTest
Trapnewspapers
TrapnewspapersTest
Hiking
HikingTest
Maze
MazeTest
Spannerlearning
SpannerlearningTest
Navigation1
Navigation1Test
Navigation2
Navigation2Test
Navigation3
Navigation3Test
Navigation4
Navigation4Test
Navigation5
Navigation5Test
Navigation6
Navigation6Test
Navigation7
Navigation7Test
Navigation8
Navigation8Test
Navigation9
Navigation9Test
Navigation10
Navigation10Test
Robotouille
```

and on ys749/dev/refactor, its
```
Gripper
GripperTest
Easygripper
EasygripperTest
Onearmedgripper
OnearmedgripperTest
Tinyonearmedgripper
TinyonearmedgripperTest
Lifelong_tiny_gripper
Lifelong_tiny_gripperTest
Rearrangement
RearrangementTest
Sokoban
SokobanTest
Minecraft
MinecraftTest
Depot
DepotTest
Baking
BakingTest
Blocks
BlocksTest
Derivedblocks
DerivedblocksTest
Toomanyblocks
ToomanyblocksTest
Lifelong_blocks6
Lifelong_blocks6Test
Travel
TravelTest
Doors
DoorsTest
Casino
CasinoTest
Hanoi
HanoiTest
Hanoi_operator_actions
Hanoi_operator_actionsTest
Tsp
TspTest
Tsp_operator_actions
Tsp_operator_actionsTest
Slidetile
SlidetileTest
Elevator
ElevatorTest
Ferry
FerryTest
Meetpass
MeetpassTest
Footwear
FootwearTest
Easyblocks
EasyblocksTest
Conditionalblocks
ConditionalblocksTest
Conditionalferry
ConditionalferryTest
Blocks_operator_actions
Blocks_operator_actionsTest
Generated_blocks
Generated_blocksTest
Blocks_medium
Blocks_mediumTest
Manyblocksnopiles
ManyblocksnopilesTest
Manyexplodingblockssmallpiles
ManyexplodingblockssmallpilesTest
Manyblockssmallpiles
ManyblockssmallpilesTest
Manyblockssmallpilesnoclear
ManyblockssmallpilesnoclearTest
Manyblockssmallpilesnohand
ManyblockssmallpilesnohandTest
Manyblockssmallpilesnoclearhand
ManyblockssmallpilesnoclearhandTest
Quantifiedblocks
QuantifiedblocksTest
Quantifiedblocks2
Quantifiedblocks2Test
Quantifiedblocks3
Quantifiedblocks3Test
Equalityblocks
EqualityblocksTest
Equalityblocks2
Equalityblocks2Test
Manygrid
ManygridTest
Manylogistics
ManylogisticsTest
Manymiconic
ManymiconicTest
Manygripper
ManygripperTest
Manyferry
ManyferryTest
Glibblocks
GlibblocksTest
Glibrearrangement
GlibrearrangementTest
Glibdoors
GlibdoorsTest
Tireworld
TireworldTest
Manytireworld
ManytireworldTest
Fridge
FridgeTest
Snake
SnakeTest
River
RiverTest
Explodingblocks
ExplodingblocksTest
Newspapers
NewspapersTest
Easynewspapers
EasynewspapersTest
Trapnewspapers
TrapnewspapersTest
Hiking
HikingTest
Maze
MazeTest
Spannerlearning
SpannerlearningTest
Navigation1
Navigation1Test
Navigation2
Navigation2Test
Navigation3
Navigation3Test
Navigation4
Navigation4Test
Navigation5
Navigation5Test
Navigation6
Navigation6Test
Navigation7
Navigation7Test
Navigation8
Navigation8Test
Navigation9
Navigation9Test
Navigation10
Navigation10Test
Robotouille
Robotouille
```

**Comment by yash-s20** [comment]
The only things that are really changed in this are import locations. Could that be a reason for the re-register @chalo2000 ?

**Comment by yash-s20** [comment]
Found the issue and fixed

**Review by chalo2000 — APPROVED** [review]
Tested on my end and I think things look good. From now on we'll use absolute paths to access things and we'll run all scripts from the root level. Or, if we want to use it elsewhere, include it in the __init__ of the `robotouille` directory.

**Review by chalo2000 — CHANGES_REQUESTED** [review]
Actually one last thing I would add is closing an environment once the loop ends. I imported simulator and ran a loop and the window stayed open.

**Comment by yash-s20** [comment]
my WSL's clock is screwed up so the commit shows before your comment but I've just pushed the change to quit once the goal is reached.

**Pull request merged**
